In [1]:
import sys
import numpy as np



### Concatenação com NumPy

In [2]:
vetor = np.ones(4)
vetor

array([1., 1., 1., 1.])

In [3]:
vetor2 = np.arange(15)
vetor2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Concatenar vetores
vetor3 = np.concatenate((vetor, vetor2))
vetor3

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

### Join

In [5]:
#Criar array com numpy de 4 por 4
vetor4 = np.zeros((4,4))
#Criar array com numpy de 4 por 4
vetor5 = np.ones((4,4))



In [6]:
print(vetor4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(vetor5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
?np.vstack

Signature: np.vstack(tup)
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
hstac

In [9]:
matrizVertical = np.vstack((vetor4, vetor5)) #preenchendo primeiro as linhas
matrizVertical.shape

(8, 4)

In [10]:
print(matrizVertical)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
matrizHorizontal = np.hstack((vetor4, vetor5)) #preenchendo primeiro as colunas
matrizHorizontal.shape

(4, 8)

In [12]:
print(matrizHorizontal)

[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [14]:
matrizABC = np.vstack((a,b,c)) #preenchendo primeiro as linhas
matrizABC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
?np.column_stack

Signature: np.column_stack(tup)
Docstring:
Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns
to make a single 2-D array. 2-D arrays are stacked as-is,
just like with `hstack`.  1-D arrays are turned into 2-D columns
first.

Parameters
----------
tup : sequence of 1-D or 2-D arrays.
    Arrays to stack. All of them must have the same first dimension.

Returns
-------
stacked : 2-D array
    The array formed by stacking the given arrays.

See Also
--------
stack, hstack, vstack, concatenate

Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.column_stack((a,b))
array([[1, 2],
       [2, 3],
       [3, 4]])
File:      c:\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Type:      function


In [16]:
matrizABC = np.column_stack((a,b,c)) #preenchendo primeiro as colunas a cada join nova coluna
matrizABC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
?np.row_stack

Signature: np.row_stack(tup)
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
hs

In [18]:
matrizABC = np.row_stack((a,b,c)) #preenchendo primeiro as linhas a cada join nova linha
matrizABC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Split

In [19]:
#Criando array de 16 posições e modificando ele para 4x4
array1 = np.arange(16).reshape(4,4); array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
[array_p1 , array_p2] = np.hsplit(array1, 2) #divide verticalmente

In [25]:
array_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
array_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [26]:
[array_p1 , array_p2] = np.vsplit(array1, 2) #divide horizontalmente

In [28]:
array_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
array_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])