In [1]:
#importar NUMPY
import numpy as np

In [2]:
#criar array de uma dimensão com NP
arrayUnidimencional = np.array([10, 20 , 40 , 50, 2])

In [3]:
#array de 2 dimensões
arrayBidimencional = np.array([[20 , 10 , 20], [15, 25 , 15]])

In [4]:
#Verificação 
arrayUnidimencional

array([10, 20, 40, 50,  2])

In [5]:
arrayBidimencional

array([[20, 10, 20],
       [15, 25, 15]])

In [6]:
#Shape mostra a quantidade de indices e formato
arrayUnidimencional.shape

(5,)

In [7]:
arrayBidimencional.shape

(2, 3)

In [8]:
#verificar quantas dimenções existem
arrayBidimencional.ndim

2

In [9]:
#arange cria uma estrutura de dados
arranjo = np.arange(10)

In [10]:
arranjo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#começa em 0 vai até o valor 50 e pula de 10 em 10
arranjoT = np.arange (1, 50 , 10)

In [12]:
arranjoT

array([ 1, 11, 21, 31, 41])

In [13]:
#Criar estruturas de dados utilizando Linspace (Começo , fim , numero de indices)
arrayLinspace = np.linspace(0 , 6 , 7) ; arrayLinspace # <- executar diretamente

array([0., 1., 2., 3., 4., 5., 6.])

In [19]:
#Criando matrizes com Numpy
matriz = np.ones((20 ,10)) ;matriz

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
#tres dimenções de 0
matrizT = np.zeros((3,3,3)) ;matrizT

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [47]:
#eye valor 1 em diagonal na matriz
matrizDiagonal = np.eye(4) ;matrizDiagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#Diag faz com que podemos selecionar os valores
matrizDiagonalValue = np.diag((2, 6, 4 , 5 , 8)) ;matrizDiagonalValue

array([[2, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 8]])

NUMPY.RANDOM.RAND

In [22]:
#função rand(n) vai criar uma sequencia numérica de 0 a n
np.random.seed(100)
randomVet = np.random.rand(6) ;randomVet

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912])

In [23]:
#função randn(n) vai criar uma sequencia de numeros com distribuição normal(gaussian)
np.random.seed(100)
randomVetn = np.random.randn(6) ;randomVetn

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884])

In [26]:
T = np.empty((3,2)) ;T


array([[1.74976547, 0.3426804 ],
       [1.1530358 , 0.25243604],
       [0.98132079, 0.51421884]])

In [30]:
#NumPy Tile
np.array([[1, 2], [3,4]])

array([[1, 2],
       [3, 4]])

In [34]:
#multiplica horizontalmente
np.tile(np.array([[1, 2], [3, 2]]), 4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 2, 3, 2, 3, 2, 3, 2]])

In [35]:
np.tile(np.array([[1, 2], [3, 2]]), (2,2))

array([[1, 2, 1, 2],
       [3, 2, 3, 2],
       [1, 2, 1, 2],
       [3, 2, 3, 2]])

In [36]:
arrayTipe = np.array([8, 2, -5 , 3], dtype='float')

In [37]:
arrayTipe

array([ 8.,  2., -5.,  3.])

In [38]:
arrayTipe.dtype

dtype('float64')

In [39]:
array20 = np.array([2, 3 , 5.6 , -20])

In [40]:
array20.dtype

dtype('float64')

In [45]:
arrayS = np.array(['Analise' , 'de' , 'Dados'])

In [46]:
arrayS.dtype

dtype('<U7')

In [47]:
arrayBool = np.array([True , False])

In [48]:
arrayBool.dtype

dtype('bool')

In [50]:
#como se fosse INT
array20.astype(int)

array([  2,   3,   5, -20])

In [51]:
#Operações Aritméticas com Arrays

In [54]:
#criar array começando em 0 com 10 posições , a cada posição multiplica o valor base por 5 sendo o ultimo indice valor 9.
array = np.arange(0,10) * 5 ;array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [55]:
array2 = np.arange(0, 10);array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#Elevar um Array de 5 posições na potencia 2
arrayPot = np.arange(7) ** 3;arrayPot

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

In [63]:
#pega o valor base dos indices e soma 1
arrayPlus = np.arange(0,30) + 1;arrayPlus

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:
#subtração
arraySub = np.arange(0,30) -1;arraySub

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [65]:
array10 = np.arange(0,30, 3) + 3
array11 = np.arange(1,11)

In [66]:
array10

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [67]:
array11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
#Subtrair arrays
array10 - array11

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
#adição
array10 + array11

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [70]:
#multiplicar
array10 * array11

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [77]:
arr1 = np.array([True, False , True , True])
arr2 = np.array([True,True , False , True])

In [78]:
np.logical_and(arr1 ,arr2)

array([ True, False, False,  True])