In [1]:
#importar NUMPY
import numpy as np

In [14]:
#criar array de uma dimensão com NP
arrayUnidimencional = np.array([10, 20 , 40 , 50, 2])

In [17]:
#array de 2 dimensões
arrayBidimencional = np.array([[20 , 10 , 20], [15, 25 , 15]])

In [12]:
#Verificação 
arrayUnidimencional

array([10, 20, 40, 50])

In [11]:
arrayBidimencional

array([[20, 10, 20],
       [15, 25, 15]])

In [15]:
#Shape mostra a quantidade de indices e formato
arrayUnidimencional.shape

(5,)

In [18]:
arrayBidimencional.shape

(2, 3)

In [19]:
#verificar quantas dimenções existem
arrayBidimencional.ndim

2

In [20]:
#arange cria uma estrutura de dados
arranjo = np.arange(10)

In [21]:
arranjo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#começa em 0 vai até o valor 50 e pula de 10 em 10
arranjoT = np.arange (1, 50 , 10)

In [29]:
arranjoT

array([ 1, 11, 21, 31, 41])

In [33]:
#Criar estruturas de dados utilizando Linspace (Começo , fim , numero de indices)
arrayLinspace = np.linspace(0 , 6 , 7) ; arrayLinspace # <- executar diretamente

array([0., 1., 2., 3., 4., 5., 6.])

In [35]:
#Criando matrizes com Numpy
matriz = np.ones((5 ,5)) ;matriz

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
#tres dimenções de 0
matrizT = np.zeros((3,3,3)) ;matrizT

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [47]:
#eye valor 1 em diagonal na matriz
matrizDiagonal = np.eye(4) ;matrizDiagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
#Diag faz com que podemos selecionar os valores
matrizDiagonalValue = np.diag((2, 6, 4 , 5 , 8)) ;matrizDiagonalValue

array([[2, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 8]])

NUMPY.RANDOM.RAND

In [63]:
#função rand(n) vai criar uma sequencia numérica de 0 a n
np.random.seed(100)
randomVet = np.random.rand(6) ;randomVet

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912])

In [64]:
#função randn(n) vai criar uma sequencia de numeros com distribuição normal(gaussian)
np.random.seed(100)
randomVetn = np.random.randn(6) ;randomVetn

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884])

In [68]:
T = np.empty((3,2)) ;T
T

array([[1.74976547, 0.3426804 ],
       [1.1530358 , 0.25243604],
       [0.98132079, 0.51421884]])