In [1]:
#importar NUMPY
import numpy as np

In [14]:
#criar array de uma dimensão com NP
arrayUnidimencional = np.array([10, 20 , 40 , 50, 2])

In [17]:
#array de 2 dimensões
arrayBidimencional = np.array([[20 , 10 , 20], [15, 25 , 15]])

In [12]:
#Verificação 
arrayUnidimencional

array([10, 20, 40, 50])

In [11]:
arrayBidimencional

array([[20, 10, 20],
       [15, 25, 15]])

In [15]:
#Shape mostra a quantidade de indices e formato
arrayUnidimencional.shape

(5,)

In [18]:
arrayBidimencional.shape

(2, 3)

In [19]:
#verificar quantas dimenções existem
arrayBidimencional.ndim

2

In [20]:
#arange cria uma estrutura de dados
arranjo = np.arange(10)

In [21]:
arranjo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#começa em 0 vai até o valor 50 e pula de 10 em 10
arranjoT = np.arange (1, 50 , 10)

In [29]:
arranjoT

array([ 1, 11, 21, 31, 41])