In [1]:
import numpy as np
import sys
print(sys.version)
np.__version__

3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]


'1.20.3'

In [2]:
#Criar array em numpy é com np.arange
vetor = np.arange(15) ; vetor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
 #help
 ?vetor

Type:            ndarray
String form:     [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Length:          15
File:            c:\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of in

In [4]:
vetor.mean() #media

7.0

In [5]:
vetor.std() #desvio padrao

4.320493798938574

In [6]:
vetor.min() #minimo

0

In [7]:
vetor.sum() #soma

105

In [8]:
vetor.max() #maximo

14

## Utilizar List Comprehension com NumPy

In [9]:
[x * x for x in vetor] #list comprehension com NumPy 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [10]:
[x ** 2 for x in vetor] #list comprehension com NumPy

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [11]:
[x * x for x in vetor if x % 2 == 0] #retorna os pares

[0, 4, 16, 36, 64, 100, 144, 196]

In [12]:
#Utilizar Funções Lambda em arrays NumPy
list(filter(lambda x: x % 2 == 0 , vetor)) #retorna os pares

[0, 2, 4, 6, 8, 10, 12, 14]

In [13]:
def calcQuad(num):
    return num ** 2

In [14]:
vetor[vetor % 2 == 0] #retorna os pares

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Teste performace

In [15]:
#Teste de velocidade de execução com List Comprehension
%timeit [x for x in vetor if x % 2 == 0] #retorna os pares



10.8 µs ± 541 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
#Teste de Performance usando NumPy
%timeit vetor[vetor % 2 == 0]

4.25 µs ± 37.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
vetor > 8 #retorna os valores maiores que 8 boolean

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [18]:
vetor[vetor > 8] #retorna os valores maiores que 8 

array([ 9, 10, 11, 12, 13, 14])

In [21]:
(vetor >8) & ( vetor < 10) #retorna os valores maiores que 8 e menores que 10

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False])

In [23]:
vetor[(vetor > 8) & (vetor < 10)] #retorna os valores maiores que 8 e menores que 10

array([9])

In [33]:
#criar array com numpy e list comprehension
vetor2 = np.array([x ** 3 for x in range(1 , 20)]) 
vetor2

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [37]:
vetor2 = np.array([True for x in range(1,15)])
vetor2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])