In [1]:
import numpy as np

In [2]:
array1 = np.array([[20 , 30 , 40],[10 , 15 , 20]]); array1

array([[20, 30, 40],
       [10, 15, 20]])

In [3]:
#transpor
array1.T

array([[20, 10],
       [30, 15],
       [40, 20]])

In [4]:
np.transpose(array1) ;array1

array([[20, 30, 40],
       [10, 15, 20]])

In [7]:
array2 = np.array([[10 , 20 , 30]]) ;array2

array([[10, 20, 30]])

In [10]:
array2.T 

array([[10],
       [20],
       [30]])

In [11]:
#somando matrizes
array2.T + array2

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [14]:
#criação de um array com 2 arranjos de dados
array3  = np.array([np.arange(1,6), np.arange(10,15)])

In [15]:
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [16]:
#transformar matriz em array
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [17]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [26]:
#criar uma matriz aleatória
np.random.seed(100)
array4 = np.random.randint(1 , 10, size =(6,6)) ;array4

array([[9, 9, 4, 8, 8, 1],
       [5, 3, 6, 3, 3, 3],
       [2, 1, 9, 5, 1, 7],
       [3, 5, 2, 6, 4, 5],
       [5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6]])

In [22]:
#dentro do array se existe numero divisivel por 7 que o resto é 0
np.any((array4 % 7) == 0)

False

In [23]:
#verificação se existem valores divisiveis por 3
np.any((array4 % 3) == 0)

True

In [25]:
#todos valores do array 4 são menores que 11 ?
np.all(array4 < 11)

True

In [27]:
arrayRe = np.arange(1,16)

In [28]:
arrayRe

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
arrayRe.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
#Criar array
arrayOrd = np.array([[10 , -2], [9 , 5]])

In [38]:
arrayOrd

array([[10, -2],
       [ 9,  5]])

In [40]:
#ordenar array por linhas
arrayOrd.sort(axis = 1) ;arrayOrd

array([[-2, 10],
       [ 5,  9]])

In [41]:
#ordenar array por colun
arrayOrd.sort(axis = 0);arrayOrd

array([[-2,  9],
       [ 5, 10]])